[project]
name = "portfolio-dashboard"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "foliotrack",
    "plotly>=6.3.0",
    "streamlit>=1.50.0",
]

[tool.uv.sources]
foliotrack = { path = "../foliotrack" }
